import type {
  FormationType,
  PlayerRoleData,
  FormationPreset,
  PlayerDuty,
} from "@/types/tactic";

export const formationPresets: FormationPreset[] = [
  {
    formation: "4-2-3-1",
    label: "4-2-3-1",
    description: "The modern classic. Two holding midfielders support a creative attacking midfielder with wingers providing width.",
    // Order: GK | LB CB CB RB | DM DM | AML AMC AMR | ST
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 35, y: 52 }, { x: 65, y: 52 },
      { x: 15, y: 34 }, { x: 50, y: 34 }, { x: 85, y: 34 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "4-3-3",
    label: "4-3-3",
    description: "Wide forwards stretch the opposition. Three midfielders offer balance between defense and attack.",
    // Order: GK | LB CB CB RB | CM DM CM | LW ST RW
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 35, y: 44 }, { x: 50, y: 56 }, { x: 65, y: 44 },
      { x: 20, y: 18 }, { x: 50, y: 10 }, { x: 80, y: 18 },
    ],
  },
  {
    formation: "4-4-2",
    label: "4-4-2",
    description: "The traditional English setup. Two banks of four with a classic strike partnership.",
    positions: [
      { x: 50, y: 88 }, { x: 10, y: 55 }, { x: 25, y: 72 }, { x: 75, y: 72 },
      { x: 90, y: 55 }, { x: 10, y: 40 }, { x: 35, y: 42 },
      { x: 65, y: 42 }, { x: 90, y: 40 }, { x: 35, y: 18 },
      { x: 65, y: 18 },
    ],
  },
  {
    formation: "3-5-2",
    label: "3-5-2",
    description: "Wing-backs provide width as three center-backs form a solid defensive base with two strikers.",
    positions: [
      { x: 50, y: 88 }, { x: 32, y: 72 }, { x: 50, y: 74 },
      { x: 68, y: 72 }, { x: 20, y: 46 }, { x: 40, y: 52 },
      { x: 50, y: 44 }, { x: 60, y: 52 }, { x: 80, y: 46 },
      { x: 35, y: 18 }, { x: 65, y: 18 },
    ],
  },
  {
    formation: "5-3-2",
    label: "5-3-2",
    description: "Ultra-defensive shape with wing-backs. Counter-attack specialist formation.",
    positions: [
      { x: 50, y: 88 }, { x: 20, y: 74 }, { x: 50, y: 78 },
      { x: 80, y: 74 }, { x: 10, y: 48 }, { x: 90, y: 48 },
      { x: 35, y: 52 }, { x: 50, y: 42 }, { x: 65, y: 52 },
      { x: 35, y: 18 }, { x: 65, y: 18 },
    ],
  },
  {
    formation: "3-4-3",
    label: "3-4-3",
    description: "Attacking formation with wing-backs pushing high. Three forwards apply constant pressure on opposing defenders.",
    positions: [
      { x: 50, y: 88 }, { x: 32, y: 72 }, { x: 50, y: 74 },
      { x: 68, y: 72 }, { x: 20, y: 46 }, { x: 40, y: 48 },
      { x: 60, y: 48 }, { x: 80, y: 46 }, { x: 25, y: 16 },
      { x: 50, y: 10 }, { x: 75, y: 16 },
    ],
  },
  {
    formation: "4-2-2-2",
    label: "4-2-2-2",
    description: "Brazilian Box. Two DMs and two AMs create a compact midfield box, with two strikers leading the line.",
    // Order: GK | LB CB CB RB | DM DM | AM AM | ST ST
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 35, y: 52 }, { x: 65, y: 52 },
      { x: 35, y: 34 }, { x: 65, y: 34 },
      { x: 35, y: 16 }, { x: 65, y: 16 },
    ],
  },
  {
    formation: "4-1-4-1",
    label: "4-1-4-1",
    description: "A solid DM shields the back four. Four midfielders offer width and numbers in the middle third.",
    // Order: GK | LB CB CB RB | DM | LM CM CM RM | ST
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 50, y: 58 },
      { x: 15, y: 42 }, { x: 38, y: 46 }, { x: 62, y: 46 }, { x: 85, y: 42 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "4-4-1-1",
    label: "4-4-1-1",
    description: "The Mourinho special. A second striker or #10 operates between the lines behind a lone target man.",
    // Order: GK | LB CB CB RB | LM CM CM RM | SS | ST
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 12, y: 46 }, { x: 38, y: 48 }, { x: 62, y: 48 }, { x: 88, y: 46 },
      { x: 50, y: 28 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "5-2-3",
    label: "5-2-3",
    description: "Three center-backs with attacking wing-backs. Wide forwards stretch play and create overloads in the final third.",
    positions: [
      { x: 50, y: 88 }, { x: 25, y: 74 }, { x: 50, y: 78 },
      { x: 75, y: 74 }, { x: 10, y: 48 }, { x: 90, y: 48 },
      { x: 35, y: 50 }, { x: 65, y: 50 },
      { x: 25, y: 16 }, { x: 50, y: 10 }, { x: 75, y: 16 },
    ],
  },
  {
    formation: "4-2-4",
    label: "4-2-4",
    description: "Ultra-attacking shape with four forwards. Risky but devastating — the FM26 community's top-scoring formation in tests.",
    // Order: GK | LB CB CB RB | DM DM (half-spaces) | LW ST ST RW (flat front four)
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 30, y: 50 }, { x: 70, y: 50 },
      { x: 15, y: 18 }, { x: 40, y: 14 }, { x: 60, y: 14 }, { x: 85, y: 18 },
    ],
  },
  {
    formation: "3-4-2-1",
    label: "3-4-2-1",
    description: "Conte's trademark. Two #10s behind a lone striker with wing-backs providing width. Extremely solid through the middle.",
    positions: [
      { x: 50, y: 88 }, { x: 32, y: 72 }, { x: 50, y: 74 },
      { x: 68, y: 72 }, { x: 15, y: 46 }, { x: 85, y: 46 },
      { x: 35, y: 52 }, { x: 65, y: 52 },
      { x: 35, y: 30 }, { x: 65, y: 30 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "4-3-2-1",
    label: "4-3-2-1",
    description: "Christmas Tree. Narrow and compact. Two advanced playmakers operate behind a solo striker, overwhelming the opponent's midfield.",
    // Order: GK | LB CB CB RB | CM CM CM | AM AM | ST (Christmas Tree)
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 30, y: 52 }, { x: 50, y: 48 }, { x: 70, y: 52 },
      { x: 35, y: 30 }, { x: 65, y: 30 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "4-1-2-1-2",
    label: "4-1-2-1-2",
    description: "Diamond midfield. A DM anchors, two CMs shuttle, and a #10 creates. Two strikers give you vertical threat against any back line.",
    // Order: GK | LB CB CB RB | DM | CM CM | AM | ST ST (Diamond)
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 50, y: 58 },
      { x: 30, y: 44 }, { x: 70, y: 44 },
      { x: 50, y: 30 },
      { x: 35, y: 14 }, { x: 65, y: 14 },
    ],
  },
];

export const playerRoles: PlayerRoleData[] = [
  {
    id: "sweeper-keeper",
    name: "Sweeper Keeper",
    abbr: "SK",
    category: "goalkeeper",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Rushing Out", "First Touch", "Passing", "Composure", "Acceleration", "Decisions"],
    description: "A goalkeeper who sweeps up balls behind the defensive line and initiates counter-attacks with long distribution.",
    bestFormations: ["4-2-3-1", "4-3-3", "5-3-2"],
  },
  {
    id: "goalkeeper",
    name: "Goalkeeper",
    abbr: "GK",
    category: "goalkeeper",
    availableDuties: ["defend"],
    keyAttributes: ["Aerial Reach", "Command of Area", "Handling", "Reflexes", "Positioning", "Decisions"],
    description: "The standard goalkeeper role. Stays between the sticks, organizes the defense, and makes saves.",
    bestFormations: ["4-2-3-1", "4-3-3", "4-4-2", "3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "ball-playing-defender",
    name: "Ball-Playing Defender",
    abbr: "BPD",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Composure", "Vision", "First Touch", "Technique", "Decisions"],
    description: "A center-back who builds play from the back with accurate passing and composure under pressure.",
    bestFormations: ["4-2-3-1", "4-3-3", "3-5-2"],
  },
  {
    id: "central-defender",
    name: "Centre-Back",
    abbr: "CD",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Tackling", "Marking", "Heading", "Positioning", "Strength", "Jumping Reach"],
    description: "The traditional no-nonsense defender. Wins aerial duels and makes crucial tackles.",
    bestFormations: ["4-4-2", "5-3-2"],
  },
  {
    id: "full-back",
    name: "Full-Back",
    abbr: "FB",
    category: "defender",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Tackling", "Stamina", "Acceleration", "Crossing", "Work Rate", "Positioning"],
    description: "Balanced wide defender who supports both attack and defense from the flanks.",
    bestFormations: ["4-2-3-1", "4-3-3", "4-4-2"],
  },
  {
    id: "wing-back",
    name: "Wing-Back",
    abbr: "WB",
    category: "defender",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Stamina", "Crossing", "Dribbling", "Acceleration", "Work Rate", "Off the Ball"],
    description: "An attacking-minded wide player who provides the main source of width in formations without wingers.",
    bestFormations: ["3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "deep-lying-playmaker",
    name: "Deep-Lying Playmaker",
    abbr: "DLP",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Vision", "Technique", "Decisions", "Composure", "First Touch"],
    description: "A midfield orchestrator who dictates tempo from deep positions with incisive passing range.",
    bestFormations: ["4-2-3-1", "4-3-3", "3-5-2"],
  },
  {
    id: "box-to-box-midfielder",
    name: "Box-to-Box Midfielder",
    abbr: "BBM",
    category: "midfielder",
    availableDuties: ["support"],
    keyAttributes: ["Stamina", "Work Rate", "Passing", "Tackling", "Long Shots", "Off the Ball"],
    description: "An energetic midfielder who contributes at both ends of the pitch with relentless running.",
    bestFormations: ["4-3-3", "4-4-2", "3-5-2"],
  },
  {
    id: "advanced-playmaker",
    name: "Advanced Playmaker",
    abbr: "AP",
    category: "midfielder",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Vision", "Passing", "Technique", "Decisions", "Flair", "First Touch"],
    description: "The creative hub operating between the lines, threading through balls and unlocking defenses.",
    bestFormations: ["4-2-3-1", "4-3-3"],
  },
  {
    id: "inside-forward",
    name: "Inside Forward",
    abbr: "IF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Dribbling", "Finishing", "Acceleration", "Off the Ball", "Composure", "Technique"],
    description: "Cuts inside from wide positions to score goals, acting more like a striker than a traditional winger.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "target-forward",
    name: "Target Forward",
    abbr: "TF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Strength", "Heading", "Jumping Reach", "First Touch", "Bravery", "Balance"],
    description: "A physical presence who holds up the ball and brings teammates into play with knock-downs and layoffs.",
    bestFormations: ["4-4-2", "3-5-2"],
  },
  // === FM26 NEW ROLES ===
  {
    id: "line-holding-keeper",
    name: "Line-Holding Keeper",
    abbr: "LHK",
    category: "goalkeeper",
    availableDuties: ["defend"],
    keyAttributes: ["Aerial Reach", "Reflexes", "Handling", "Positioning", "Command of Area", "Decisions"],
    description: "A traditional goalkeeper introduced in FM26 who holds his line and stays deep — ideal for defences that sit back and protect the box.",
    bestFormations: ["4-4-2", "5-3-2", "4-2-3-1"],
  },
  {
    id: "overlapping-centre-back",
    name: "Overlapping Centre-Back",
    abbr: "OCB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Pace", "Off the Ball", "Passing", "Work Rate", "Acceleration", "Positioning"],
    description: "A FM26 centre-back role for three-at-the-back systems who steps out and overlaps on the flank, adding an extra body in the final third.",
    bestFormations: ["3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "playmaking-wing-back",
    name: "Playmaking Wing-Back",
    abbr: "PWB",
    category: "defender",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Passing", "Crossing", "Vision", "Dribbling", "Work Rate", "Stamina"],
    description: "The advanced FM26 wing-back role that drifts inside to dictate play, creating overloads while the wide forward stretches the pitch.",
    bestFormations: ["3-5-2", "3-4-3", "5-2-3"],
  },
  {
    id: "channel-midfielder",
    name: "Channel Midfielder",
    abbr: "CHM",
    category: "midfielder",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Off the Ball", "Acceleration", "Passing", "First Touch", "Decisions", "Teamwork"],
    description: "A new FM26 midfielder who attacks the half-spaces between the lines, arriving late in the box and combining between midfield and attack.",
    bestFormations: ["4-3-3", "4-2-3-1", "3-4-3"],
  },
  // === FM26 STANDARD ROLES (real in-game names) ===
  {
    id: "central-midfielder",
    name: "Central Midfielder",
    abbr: "CM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Tackling", "Stamina", "Positioning", "Teamwork", "Decisions"],
    description: "The all-round central midfielder who keeps the team's shape, recycling possession and plugging gaps on both sides of the ball.",
    bestFormations: ["4-4-2", "4-3-3"],
  },
  {
    id: "winger",
    name: "Winger",
    abbr: "W",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Crossing", "Dribbling", "Pace", "Acceleration", "Technique", "Agility"],
    description: "The traditional wide attacker who hugs the touchline, beats his man and delivers crosses from the byline.",
    bestFormations: ["4-3-3", "4-2-3-1", "4-4-2", "4-2-4"],
  },
  {
    id: "tracking-winger",
    name: "Tracking Winger",
    abbr: "TW",
    category: "forward",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Stamina", "Pace", "Tackling", "Marking", "Teamwork"],
    description: "An FM26 out-of-possession wide role that tracks opposition full-backs up and down the flank before attacking on the turn.",
    bestFormations: ["3-4-3", "4-4-2"],
  },
  {
    id: "pressing-central-midfielder",
    name: "Pressing Central Midfielder",
    abbr: "PCM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Tackling", "Aggression", "Work Rate", "Stamina", "Anticipation", "Positioning"],
    description: "FM26's ball-winning engine — hunts possession relentlessly in midfield and feeds teammates with simple, secure passes.",
    bestFormations: ["4-4-2", "4-2-3-1", "3-5-2"],
  },
  {
    id: "defensive-midfielder",
    name: "Defensive Midfielder",
    abbr: "DM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Tackling", "Positioning", "Marking", "Strength", "Anticipation", "Concentration"],
    description: "The anchor of the midfield who sits in front of the back line, screening passes into central areas.",
    bestFormations: ["4-2-3-1", "4-1-2-1-2", "4-4-2"],
  },
  {
    id: "attacking-midfielder",
    name: "Attacking Midfielder",
    abbr: "AM",
    category: "midfielder",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Vision", "Passing", "Technique", "Off the Ball", "Flair", "Long Shots"],
    description: "A central creator in the hole between the opposition midfield and defence, linking play and arriving late in the box.",
    bestFormations: ["4-2-3-1", "4-1-2-1-2"],
  },
  {
    id: "wide-covering-central-midfielder",
    name: "Wide Covering Central Midfielder",
    abbr: "WCC",
    category: "midfielder",
    availableDuties: ["support"],
    keyAttributes: ["Stamina", "Work Rate", "Positioning", "Teamwork", "Tackling", "Pace"],
    description: "FM26's renamed Carrilero — shuttles laterally to cover the half-space and flank left by attacking full-backs and wing-backs.",
    bestFormations: ["4-1-2-1-2", "3-5-2"],
  },
  {
    id: "centre-forward",
    name: "Centre Forward",
    abbr: "CF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Finishing", "First Touch", "Off the Ball", "Composure", "Strength", "Heading"],
    description: "FM26's complete striker — leads the line, links play and finishes inside the box, the spiritual successor to the Complete Forward.",
    bestFormations: ["4-3-3", "4-2-3-1", "3-4-3"],
  },
  {
    id: "deep-lying-forward",
    name: "Deep-Lying Forward",
    abbr: "DLF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["First Touch", "Passing", "Vision", "Composure", "Off the Ball", "Technique"],
    description: "Drops off the defensive line to link midfield and attack, creating space for runners from deep.",
    bestFormations: ["4-1-2-1-2", "4-2-3-1", "4-4-2"],
  },
  {
    id: "free-role",
    name: "Free Role",
    abbr: "FR",
    category: "midfielder",
    availableDuties: ["attack"],
    keyAttributes: ["Flair", "Vision", "First Touch", "Technique", "Off the Ball", "Composure"],
    description: "FM26's successor to the Trequartista — roams the final third with a free licence to create, unbound by tactical shape.",
    bestFormations: ["4-2-3-1", "4-4-1-1"],
  },
  {
    id: "tracking-centre-forward",
    name: "Tracking Centre Forward",
    abbr: "TCF",
    category: "forward",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Stamina", "Aggression", "Tackling", "Teamwork", "Acceleration"],
    description: "A new FM26 striker who leads the press from the front and drops back to bolster midfield when defending.",
    bestFormations: ["4-2-3-1", "4-3-3"],
  },
  {
    id: "no-nonsense-keeper",
    name: "No-Nonsense Goalkeeper",
    abbr: "NGK",
    category: "goalkeeper",
    availableDuties: ["defend"],
    keyAttributes: ["Reflexes", "Handling", "Positioning", "Concentration", "Decisions", "Command of Area"],
    description: "FM26's safety-first keeper — never takes risks, clears everything long and keeps the back line honest.",
    bestFormations: ["5-3-2", "4-4-2"],
  },
  {
    id: "ball-playing-keeper",
    name: "Ball-Playing Goalkeeper",
    abbr: "BPGK",
    category: "goalkeeper",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Composure", "Vision", "First Touch", "Reflexes", "Decisions"],
    description: "A deep-lying playmaker in gloves — splits the press with line-breaking distribution from the back.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "no-nonsense-centre-back",
    name: "No-Nonsense Centre-Back",
    abbr: "NNCB",
    category: "defender",
    availableDuties: ["defend"],
    keyAttributes: ["Tackling", "Marking", "Heading", "Positioning", "Strength", "Concentration"],
    description: "Old school in the modern game — wins it, clears it, asks no questions and never plays across his own box.",
    bestFormations: ["5-3-2", "4-4-2"],
  },
  {
    id: "covering-centre-back",
    name: "Covering Centre-Back",
    abbr: "CCB",
    category: "defender",
    availableDuties: ["defend"],
    keyAttributes: ["Positioning", "Anticipation", "Acceleration", "Marking", "Concentration", "Pace"],
    description: "Drops behind the defensive line to sweep danger, covering for aggressive partners and high offside traps.",
    bestFormations: ["4-2-3-1", "3-5-2"],
  },
  {
    id: "stopping-centre-back",
    name: "Stopping Centre-Back",
    abbr: "SCB",
    category: "defender",
    availableDuties: ["defend"],
    keyAttributes: ["Tackling", "Aggression", "Marking", "Strength", "Bravery", "Anticipation"],
    description: "Steps out early to meet attacks head-on, engaging strikers before they build a head of steam.",
    bestFormations: ["4-4-2", "3-4-3"],
  },
  {
    id: "advanced-centre-back",
    name: "Advanced Centre-Back",
    abbr: "ACB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Vision", "Composure", "Dribbling", "Decisions", "Positioning"],
    description: "FM26's modern libero — carries the ball into midfield during build-up to create an extra man against the press.",
    bestFormations: ["3-5-2", "3-4-3"],
  },
  {
    id: "wide-centre-back",
    name: "Wide Centre-Back",
    abbr: "WCB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Tackling", "Positioning", "Crossing", "Stamina", "Marking"],
    description: "The wide defender in a back three — holds width in build-up and steps out to engage wide runners.",
    bestFormations: ["3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "covering-wide-centre-back",
    name: "Covering Wide Centre-Back",
    abbr: "CWCB",
    category: "defender",
    availableDuties: ["defend"],
    keyAttributes: ["Positioning", "Anticipation", "Pace", "Marking", "Concentration", "Acceleration"],
    description: "The cautious half of a back three's flank — holds position, covers in behind and protects the far post.",
    bestFormations: ["3-5-2", "5-2-3"],
  },
  {
    id: "stopping-wide-centre-back",
    name: "Stopping Wide Centre-Back",
    abbr: "SWCB",
    category: "defender",
    availableDuties: ["defend"],
    keyAttributes: ["Tackling", "Aggression", "Marking", "Pace", "Strength", "Bravery"],
    description: "The aggressive half of a back three's flank — meets wide threats early and wins the ball high.",
    bestFormations: ["3-4-3", "3-5-2"],
  },
  {
    id: "holding-full-back",
    name: "Holding Full-Back",
    abbr: "HFB",
    category: "defender",
    availableDuties: ["defend"],
    keyAttributes: ["Marking", "Positioning", "Tackling", "Concentration", "Anticipation", "Pace"],
    description: "Stays home while the team presses, plugging the gap behind an advancing winger on the same flank.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "inside-full-back",
    name: "Inside Full-Back",
    abbr: "IFB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Positioning", "Marking", "Passing", "Tackling", "Concentration", "Decisions"],
    description: "Tucks into the central defensive corridor when his team attacks, tightening the box against counters.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "inverted-full-back",
    name: "Inverted Full-Back",
    abbr: "IVFB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Vision", "First Touch", "Positioning", "Stamina", "Decisions"],
    description: "Marches into central midfield in possession — an extra controller who overloads the middle of the park.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "pressing-full-back",
    name: "Pressing Full-Back",
    abbr: "PFB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Stamina", "Aggression", "Pace", "Tackling", "Marking"],
    description: "Hunts the opposition winger high up the pitch, turning the press into a four-man front line.",
    bestFormations: ["4-4-2", "4-2-3-1"],
  },
  {
    id: "holding-wing-back",
    name: "Holding Wing-Back",
    abbr: "HWB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Positioning", "Marking", "Tackling", "Stamina", "Concentration", "Anticipation"],
    description: "A wing-back with a safety brief — drops into the back line during possession to guard against counters.",
    bestFormations: ["3-5-2", "5-2-3"],
  },
  {
    id: "inside-wing-back",
    name: "Inside Wing-Back",
    abbr: "IWB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Positioning", "Marking", "Vision", "Teamwork", "Concentration"],
    description: "Drifts into the half-space to link play and screen the midfield, defending narrow out of possession.",
    bestFormations: ["3-5-2", "4-3-3"],
  },
  {
    id: "inverted-wing-back",
    name: "Inverted Wing-Back",
    abbr: "IVWB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Vision", "Positioning", "First Touch", "Stamina", "Decisions"],
    description: "Plays like a deep midfielder — inverting into the centre to control tempo and screen the back line.",
    bestFormations: ["3-4-3", "4-3-3"],
  },
  {
    id: "pressing-wing-back",
    name: "Pressing Wing-Back",
    abbr: "PRWB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Stamina", "Pace", "Aggression", "Tackling", "Marking"],
    description: "Chases the opposition wide player into their own half, leading the press from the flanks.",
    bestFormations: ["3-4-3", "5-2-3"],
  },
  {
    id: "advanced-wing-back",
    name: "Advanced Wing-Back",
    abbr: "AWB",
    category: "defender",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Stamina", "Crossing", "Pace", "Work Rate", "Dribbling", "Off the Ball"],
    description: "Plays high and wide for 90 minutes like an old-school wide midfielder, stretching the pitch and whipping in crosses.",
    bestFormations: ["3-5-2", "3-4-3"],
  },
  {
    id: "dropping-defensive-midfielder",
    name: "Dropping Defensive Midfielder",
    abbr: "DDM",
    category: "midfielder",
    availableDuties: ["defend"],
    keyAttributes: ["Positioning", "Marking", "Tackling", "Anticipation", "Composure", "Decisions"],
    description: "Falls into the back line when the team is pressed, forming a temporary back three to bypass the press.",
    bestFormations: ["4-3-3", "3-5-2"],
  },
  {
    id: "screening-defensive-midfielder",
    name: "Screening Defensive Midfielder",
    abbr: "SDM",
    category: "midfielder",
    availableDuties: ["defend"],
    keyAttributes: ["Positioning", "Marking", "Anticipation", "Concentration", "Tackling", "Decisions"],
    description: "FM26's anchor successor — parks himself in passing lanes and strangles supply into the opposition forwards.",
    bestFormations: ["4-2-3-1", "4-3-3"],
  },
  {
    id: "wide-covering-defensive-midfielder",
    name: "Wide Covering Defensive Midfielder",
    abbr: "WCDM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Stamina", "Work Rate", "Positioning", "Marking", "Pace", "Teamwork"],
    description: "Shuttles sideways to guard the flanks, protecting the space left by marauding wing-backs in front of the back line.",
    bestFormations: ["3-5-2", "3-4-3"],
  },
  {
    id: "half-back",
    name: "Half-Back",
    abbr: "HB",
    category: "midfielder",
    availableDuties: ["defend"],
    keyAttributes: ["Positioning", "Marking", "Tackling", "Anticipation", "Concentration", "Teamwork"],
    description: "Sits between the centre-backs when his team attacks, morphing a back two into a back three.",
    bestFormations: ["3-4-3", "4-1-4-1"],
  },
  {
    id: "pressing-defensive-midfielder",
    name: "Pressing Defensive Midfielder",
    abbr: "PDM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Aggression", "Stamina", "Tackling", "Anticipation", "Marking"],
    description: "Steps out of the anchor slot to hunt the ball high, triggering the press from the base of midfield.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "screening-central-midfielder",
    name: "Screening Central Midfielder",
    abbr: "SCM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Positioning", "Marking", "Anticipation", "Tackling", "Concentration", "Teamwork"],
    description: "Screens the zone in front of the back four from a central midfield berth — the shield in a two-man engine room.",
    bestFormations: ["4-4-2", "4-3-3"],
  },
  {
    id: "box-to-box-playmaker",
    name: "Box-to-Box Playmaker",
    abbr: "B2BP",
    category: "midfielder",
    availableDuties: ["support"],
    keyAttributes: ["Stamina", "Work Rate", "Passing", "Vision", "Off the Ball", "First Touch"],
    description: "FM26's rebadged Roaming Playmaker — roams box to box with the ball at his feet, dictating tempo everywhere he goes.",
    bestFormations: ["4-3-3", "4-4-2"],
  },
  {
    id: "midfield-playmaker",
    name: "Midfield Playmaker",
    abbr: "MP",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Vision", "Composure", "First Touch", "Technique", "Decisions"],
    description: "FM26's AP-DLP hybrid — a single creative controller who dictates from deep or between the lines.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "wide-midfielder",
    name: "Wide Midfielder",
    abbr: "WM",
    category: "midfielder",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Stamina", "Crossing", "Work Rate", "Passing", "Positioning", "Tackling"],
    description: "The balanced wide midfielder of a flat four — defends his flank, holds width and supports the striker.",
    bestFormations: ["4-4-2", "4-1-4-1"],
  },
  {
    id: "tracking-wide-midfielder",
    name: "Tracking Wide Midfielder",
    abbr: "TWM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Stamina", "Marking", "Tackling", "Positioning", "Teamwork"],
    description: "Does the dirty work on the flank — tracks the opposition full-back before sprinting 60 yards to join the next attack.",
    bestFormations: ["4-4-2", "4-1-4-1"],
  },
  {
    id: "wide-central-midfielder",
    name: "Wide Central Midfielder",
    abbr: "WCM",
    category: "midfielder",
    availableDuties: ["support"],
    keyAttributes: ["Stamina", "Passing", "Work Rate", "Positioning", "Teamwork", "Tackling"],
    description: "The third man in a midfield three deployed wide — plays like a central midfielder with a touchline starting spot.",
    bestFormations: ["4-3-3", "3-5-2"],
  },
  {
    id: "wide-outlet-midfielder",
    name: "Wide Outlet Midfielder",
    abbr: "WOM",
    category: "midfielder",
    availableDuties: ["attack"],
    keyAttributes: ["Pace", "Acceleration", "Off the Ball", "Stamina", "Finishing", "Crossing"],
    description: "Stays high and wide with no defensive brief — the outlet who turns defence into attack in two passes.",
    bestFormations: ["4-4-2", "5-3-2"],
  },
  {
    id: "tracking-attacking-midfielder",
    name: "Tracking Attacking Midfielder",
    abbr: "TAM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Stamina", "Tackling", "Positioning", "Teamwork", "Vision"],
    description: "The number 10 who defends — drops into midfield out of possession to make the block a compact six.",
    bestFormations: ["4-2-3-1", "4-4-1-1"],
  },
  {
    id: "central-outlet-attacking-midfielder",
    name: "Central Outlet Attacking Midfielder",
    abbr: "COAM",
    category: "midfielder",
    availableDuties: ["attack"],
    keyAttributes: ["Off the Ball", "Acceleration", "Finishing", "Anticipation", "Composure", "Positioning"],
    description: "Lives on the shoulder of the last defender — FM26's high-line number 10 built for lightning counters.",
    bestFormations: ["4-2-3-1", "4-4-1-1"],
  },
  {
    id: "splitting-outlet-attacking-midfielder",
    name: "Splitting Outlet Attacking Midfielder",
    abbr: "SOAM",
    category: "midfielder",
    availableDuties: ["attack"],
    keyAttributes: ["Pace", "Off the Ball", "Acceleration", "Crossing", "Anticipation", "Dribbling"],
    description: "The wide-splitting runner in a high pair — stretches the pitch diagonally to open up counters.",
    bestFormations: ["4-2-3-1", "3-4-3"],
  },
  {
    id: "half-space-winger",
    name: "Half-Space Winger",
    abbr: "HSW",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Dribbling", "Off the Ball", "Acceleration", "Finishing", "First Touch", "Vision"],
    description: "Starts wide but attacks the half-space channel — the successor lane to the old inverted winger.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "inside-winger",
    name: "Inside Winger",
    abbr: "IW",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Dribbling", "Acceleration", "Finishing", "Technique", "Composure", "Off the Ball"],
    description: "Runs the byline in build-up then cuts inside onto his stronger foot — FM26's inverted-winger successor.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "inside-outlet-winger",
    name: "Inside Outlet Winger",
    abbr: "IOW",
    category: "forward",
    availableDuties: ["attack"],
    keyAttributes: ["Pace", "Off the Ball", "Acceleration", "Finishing", "Anticipation", "Composure"],
    description: "Holds a high inside position with zero defensive duties — the counter-attack dagger who kills games on the break.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "wide-outlet-winger",
    name: "Wide Outlet Winger",
    abbr: "WOW",
    category: "forward",
    availableDuties: ["attack"],
    keyAttributes: ["Pace", "Crossing", "Acceleration", "Off the Ball", "Stamina", "Dribbling"],
    description: "Stays high and wide as the escape valve — receives the long ball in space and relieves pressure instantly.",
    bestFormations: ["4-3-3", "4-4-2"],
  },
  {
    id: "wide-playmaker",
    name: "Wide Playmaker",
    abbr: "WP",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Vision", "Passing", "Technique", "Flair", "Crossing", "First Touch"],
    description: "The creator on the touchline — drifts inside with the ball to unlock defences from wide starting positions.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "wide-forward",
    name: "Wide Forward",
    abbr: "WF",
    category: "forward",
    availableDuties: ["attack"],
    keyAttributes: ["Finishing", "Off the Ball", "Acceleration", "Composure", "Pace", "Dribbling"],
    description: "A striker deployed wide — attacks the six-yard box rather than the byline, arriving on crosses and cut-backs.",
    bestFormations: ["4-3-3", "3-4-3"],
  },
  {
    id: "false-nine",
    name: "False Nine",
    abbr: "F9",
    category: "forward",
    availableDuties: ["support"],
    keyAttributes: ["First Touch", "Vision", "Passing", "Technique", "Composure", "Off the Ball"],
    description: "Drops deep to link play and drag defenders out of position, creating space for runners from midfield.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "poacher",
    name: "Poacher",
    abbr: "P",
    category: "forward",
    availableDuties: ["attack"],
    keyAttributes: ["Finishing", "Off the Ball", "Composure", "Anticipation", "Acceleration", "First Touch"],
    description: "Lives for the six-yard box — never tracks, never drifts wide, just arrives where the ball will be.",
    bestFormations: ["4-4-2", "4-2-3-1"],
  },
  {
    id: "half-space-forward",
    name: "Half-Space Forward",
    abbr: "HSF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Off the Ball", "Dribbling", "Finishing", "Acceleration", "First Touch", "Vision"],
    description: "Starts central but attacks the channel between full-back and centre-back — FM26's diagonal goal runner.",
    bestFormations: ["4-4-2", "4-3-3"],
  },
  {
    id: "second-striker",
    name: "Second Striker",
    abbr: "SS",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Off the Ball", "Finishing", "Passing", "Anticipation", "Composure", "First Touch"],
    description: "Drops off the front line to link, then attacks the box late — the classic strike partner reborn for FM26.",
    bestFormations: ["4-4-2", "4-1-2-1-2"],
  },
  {
    id: "channel-forward",
    name: "Channel Forward",
    abbr: "ChF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Acceleration", "Off the Ball", "Pace", "Finishing", "First Touch", "Work Rate"],
    description: "The tireless channel runner — stretches defences vertically with constant runs in behind the full-backs.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "central-outlet-forward",
    name: "Central Outlet Centre Forward",
    abbr: "COCF",
    category: "forward",
    availableDuties: ["attack"],
    keyAttributes: ["Off the Ball", "Finishing", "Heading", "Strength", "Anticipation", "Composure"],
    description: "Stays high and central as the counter-attack target — holds the ball up and brings the runners into play.",
    bestFormations: ["4-2-3-1", "5-3-2"],
  },
  {
    id: "splitting-outlet-forward",
    name: "Splitting Outlet Centre Forward",
    abbr: "SOCF",
    category: "forward",
    availableDuties: ["attack"],
    keyAttributes: ["Pace", "Off the Ball", "Acceleration", "Finishing", "Anticipation", "First Touch"],
    description: "Splits wide of the centre-backs when his team defends — the out-ball who turns clearances into one-v-ones.",
    bestFormations: ["4-2-3-1", "3-5-2"],
  },
];

export const styleLabels: Record<string, string> = {
  "gegenpress": "Gegenpress",
  "tiki-taka": "Tiki-Taka",
  "counter-attack": "Counter Attack",
  "wing-play": "Wing Play",
  "route-one": "Route One",
  "fluid": "Fluid Attack",
  "fluid-counter-attack": "Fluid Counter",
  "park-the-bus": "Park the Bus",
  "control-possession": "Control Possession",
};

export const styleColors: Record<string, string> = {
  "gegenpress": "bg-red-500/20 text-red-400 border-red-500/30",
  "tiki-taka": "bg-blue-500/20 text-blue-400 border-blue-500/30",
  "counter-attack": "bg-amber-500/20 text-amber-400 border-amber-500/30",
  "wing-play": "bg-purple-500/20 text-purple-400 border-purple-500/30",
  "route-one": "bg-orange-500/20 text-orange-400 border-orange-500/30",
  "fluid": "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
  "fluid-counter-attack": "bg-teal-500/20 text-teal-400 border-teal-500/30",
  "park-the-bus": "bg-slate-500/20 text-slate-400 border-slate-500/30",
  "control-possession": "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
};

export const mentalityDescriptions: Record<string, string> = {
  "very-defensive": "Extreme caution. Players stay behind the ball and rarely commit forward.",
  "defensive": "Prioritizes defensive solidity with selective counter-attacking.",
  "cautious": "Keeps possession and waits for openings without taking unnecessary risks.",
  "balanced": "A measured approach that adapts to game situations.",
  "positive": "Looks to control the game with attacking intent while maintaining defensive structure.",
  "attacking": "High-tempo attacking football focused on creating chances.",
  "very-attacking": "All-out attack. Players flood forward and take constant risks.",
};
