import { siteConfig } from "@/lib/metadata";
import { formationPresets, playerRoles } from "@/lib/tactics-data";
import type {
  PhasePlayerMap,
  PhaseType,
  PlayerDuty,
  PlayerNode,
  TacticBoardState,
  TacticPhases,
} from "@/types/tactic";

/**
 * Pure tactic-state utilities shared by the client builder and the server
 * (share landing page + OG image route). Extracted from use-tactic-builder.ts
 * so server components can import them without crossing the "use client"
 * module boundary.
 */

export const PHASE_VALUES: PhaseType[] = ["in-possession", "out-of-possession"];

function isValidPhaseMap(map: unknown, players: PlayerNode[]): boolean {
  if (!map || typeof map !== "object") return false;
  // Every current player must have a valid phase entry (drafts saved across a
  // formation change can drift — those get regenerated by ensurePhases).
  return players.every((p) => {
    const entry = (map as Record<string, unknown>)[p.id];
    return (
      entry &&
      typeof entry === "object" &&
      typeof (entry as { x?: unknown }).x === "number" &&
      typeof (entry as { y?: unknown }).y === "number"
    );
  });
}

/** Always rebuild both phase maps from the given players, discarding phase edits. */
export function freshPhases(players: PlayerNode[]): TacticPhases {
  return {
    "in-possession": Object.fromEntries(
      players.map((p) => [p.id, { x: p.x, y: p.y }])
    ),
    "out-of-possession": Object.fromEntries(
      players.map((p) => [p.id, { x: p.x, y: p.y }])
    ),
  };
}

/**
 * Migrate legacy tactic data (no phases) by duplicating the base positions
 * into both phases — roles, duties and team instructions stay untouched.
 */
export function ensurePhases(state: TacticBoardState): TacticBoardState {
  if (
    state.phases &&
    isValidPhaseMap(state.phases["in-possession"], state.players) &&
    isValidPhaseMap(state.phases["out-of-possession"], state.players)
  ) {
    return state;
  }
  return {
    ...state,
    phases: freshPhases(state.players),
  };
}

/** Players as displayed in a phase: base identities, phase coordinates. */
export function resolvePhasePlayers(
  state: TacticBoardState,
  phase: PhaseType
): PlayerNode[] {
  const map = state.phases?.[phase];
  if (!map) return state.players;
  return state.players.map((p) => {
    const entry = map[p.id];
    return entry ? { ...p, x: entry.x, y: entry.y } : p;
  });
}

export function isValidTacticState(value: unknown): value is TacticBoardState {
  if (!value || typeof value !== "object") return false;
  const v = value as Partial<TacticBoardState>;
  if (typeof v.formation !== "string") return false;
  // Football is 11-a-side; reject legacy drafts/links/imports with wrong counts
  if (!Array.isArray(v.players) || v.players.length !== 11) return false;
  const playersOk = v.players.every(
    (p) =>
      p &&
      typeof p.id === "string" &&
      typeof p.x === "number" &&
      typeof p.y === "number" &&
      typeof p.roleId === "string" &&
      (p.duty === "defend" || p.duty === "support" || p.duty === "attack")
  );
  if (!playersOk) return false;
  const ti = v.teamInstructions as TacticBoardState["teamInstructions"] | undefined;
  if (!ti || typeof ti !== "object") return false;
  return (
    typeof ti.mentality === "string" &&
    Array.isArray(ti.inPossession) &&
    Array.isArray(ti.inTransition) &&
    Array.isArray(ti.outOfPossession)
  );
}

/** Unicode-safe base64 (UTF-8 bytes). Byte-identical to the old escape/unescape path, so existing shared links keep decoding. */
function toBase64(str: string): string {
  const bytes = new TextEncoder().encode(str);
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}

function fromBase64(b64: string): string {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder().decode(bytes);
}

/** Encode a tactic state into a compact URL-safe string. */
export function encodeTacticState(state: TacticBoardState): string {
  return toBase64(JSON.stringify(state));
}

/** Decode a URL-encoded tactic state, or null if invalid. Legacy payloads without phases are migrated on decode. */
export function decodeTacticState(encoded: string): TacticBoardState | null {
  try {
    const parsed = JSON.parse(fromBase64(encoded));
    return isValidTacticState(parsed) ? ensurePhases(parsed) : null;
  } catch {
    return null;
  }
}

/**
 * Build a URL-ready `tactic` param from a content tactic's frontmatter setup,
 * so "Try in Builder" loads the exact 11 roles/duties/positions shown on the
 * tactic page instead of the formation's default preset.
 * Returns the encodeURIComponent'd payload, or null when the setup can't form
 * a valid 11-a-side board (caller should fall back to `?formation=`).
 */
export function encodeTacticSetupParam(
  formation: string,
  setup: ReadonlyArray<{ roleId: string; duty: string; x: number; y: number }> | undefined
): string | null {
  if (!setup || setup.length !== 11) return null;
  const preset = formationPresets.find((f) => f.formation === formation);
  if (!preset) return null;
  const players: PlayerNode[] = [];
  for (let i = 0; i < setup.length; i++) {
    const s = setup[i];
    const role = playerRoles.find((r) => r.id === s.roleId);
    if (!role || typeof s.x !== "number" || typeof s.y !== "number") return null;
    const duty = (role.availableDuties as readonly string[]).includes(s.duty)
      ? (s.duty as PlayerDuty)
      : role.availableDuties[0] || "support";
    players.push({
      id: `player-${i}`,
      x: s.x,
      y: s.y,
      roleId: s.roleId,
      duty,
      individualInstructions: [],
    });
  }
  const state: TacticBoardState = {
    formation: preset.formation,
    players,
    teamInstructions: {
      mentality: "balanced",
      inPossession: [],
      inTransition: [],
      outOfPossession: [],
    },
  };
  return encodeURIComponent(encodeTacticState(ensurePhases(state)));
}

/** A tactic param ready for a query string: encodeURIComponent'd base64 state. */
export function encodeTacticParam(state: TacticBoardState): string {
  return encodeURIComponent(encodeTacticState(state));
}

/**
 * Short share caption naming the shape. Kept tiny: X counts the link as 23
 * characters and the encoded tactic URL is long, so the text must stay
 * well under the 280-character limit.
 */
export function buildShareText(formationLabel: string): string {
  return `My FM26 ${formationLabel} tactic`;
}

/** Path of the share landing page carrying the full tactic payload. */
export function buildSharePath(tacticParam: string): string {
  return `/share?tactic=${tacticParam}`;
}

/** Absolute share URL (X/Facebook/Reddit/Discord all need an absolute target). */
export function buildShareUrl(tacticParam: string): string {
  return `${siteConfig.url}${buildSharePath(tacticParam)}`;
}

export type ShareTarget = "x" | "facebook" | "reddit";

/** Platform intent URLs — Discord has none, it copies the link instead. */
export function buildShareIntentUrl(
  target: ShareTarget,
  shareUrl: string,
  shareText: string
): string {
  const url = encodeURIComponent(shareUrl);
  const text = encodeURIComponent(shareText);
  switch (target) {
    case "x":
      return `https://twitter.com/intent/tweet?text=${text}&url=${url}`;
    case "facebook":
      return `https://www.facebook.com/sharer/sharer.php?u=${url}`;
    case "reddit":
      return `https://www.reddit.com/submit?url=${url}&title=${text}`;
  }
}
