import type {
  FormationType,
  PlayerRoleData,
  FormationPreset,
  PlayerDuty,
} from "@/types/tactic";

export const formationPresets: FormationPreset[] = [
  {
    formation: "4-2-3-1",
    label: "4-2-3-1",
    description: "The modern classic. Two holding midfielders support a creative attacking midfielder with wingers providing width.",
    positions: [
      { x: 50, y: 88 }, { x: 25, y: 72 }, { x: 75, y: 72 },
      { x: 50, y: 55 }, { x: 10, y: 40 }, { x: 35, y: 52 },
      { x: 65, y: 52 }, { x: 90, y: 40 }, { x: 25, y: 22 },
      { x: 75, y: 22 }, { x: 50, y: 10 },
    ],
  },
  {
    formation: "4-3-3",
    label: "4-3-3",
    description: "Wide forwards stretch the opposition. Three midfielders offer balance between defense and attack.",
    positions: [
      { x: 50, y: 88 }, { x: 25, y: 72 }, { x: 75, y: 72 },
      { x: 50, y: 55 }, { x: 10, y: 40 }, { x: 35, y: 48 },
      { x: 65, y: 48 }, { x: 90, y: 40 }, { x: 25, y: 18 },
      { x: 50, y: 10 }, { x: 75, y: 18 },
    ],
  },
  {
    formation: "4-4-2",
    label: "4-4-2",
    description: "The traditional English setup. Two banks of four with a classic strike partnership.",
    positions: [
      { x: 50, y: 88 }, { x: 25, y: 72 }, { x: 75, y: 72 },
      { x: 50, y: 55 }, { x: 10, y: 40 }, { x: 35, y: 42 },
      { x: 65, y: 42 }, { x: 90, y: 40 }, { x: 35, y: 18 },
      { x: 65, y: 18 },
    ],
  },
  {
    formation: "3-5-2",
    label: "3-5-2",
    description: "Wing-backs provide width as three center-backs form a solid defensive base with two strikers.",
    positions: [
      { x: 50, y: 88 }, { x: 32, y: 72 }, { x: 50, y: 74 },
      { x: 68, y: 72 }, { x: 20, y: 46 }, { x: 40, y: 52 },
      { x: 50, y: 44 }, { x: 60, y: 52 }, { x: 80, y: 46 },
      { x: 35, y: 18 }, { x: 65, y: 18 },
    ],
  },
  {
    formation: "5-3-2",
    label: "5-3-2",
    description: "Ultra-defensive shape with wing-backs. Counter-attack specialist formation.",
    positions: [
      { x: 50, y: 88 }, { x: 20, y: 74 }, { x: 50, y: 78 },
      { x: 80, y: 74 }, { x: 10, y: 48 }, { x: 90, y: 48 },
      { x: 35, y: 52 }, { x: 50, y: 42 }, { x: 65, y: 52 },
      { x: 35, y: 18 }, { x: 65, y: 18 },
    ],
  },
  {
    formation: "3-4-3",
    label: "3-4-3",
    description: "Attacking formation with wing-backs pushing high. Three forwards apply constant pressure on opposing defenders.",
    positions: [
      { x: 50, y: 88 }, { x: 32, y: 72 }, { x: 50, y: 74 },
      { x: 68, y: 72 }, { x: 20, y: 46 }, { x: 40, y: 48 },
      { x: 60, y: 48 }, { x: 80, y: 46 }, { x: 25, y: 16 },
      { x: 50, y: 10 }, { x: 75, y: 16 },
    ],
  },
];

export const playerRoles: PlayerRoleData[] = [
  {
    id: "sweeper-keeper",
    name: "Sweeper Keeper",
    category: "goalkeeper",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Rushing Out", "First Touch", "Passing", "Composure", "Acceleration", "Decisions"],
    description: "A goalkeeper who sweeps up balls behind the defensive line and initiates counter-attacks with long distribution.",
    bestFormations: ["4-2-3-1", "4-3-3", "5-3-2"],
  },
  {
    id: "goalkeeper",
    name: "Goalkeeper",
    category: "goalkeeper",
    availableDuties: ["defend"],
    keyAttributes: ["Aerial Reach", "Command of Area", "Handling", "Reflexes", "Positioning", "Decisions"],
    description: "The standard goalkeeper role. Stays between the sticks, organizes the defense, and makes saves.",
    bestFormations: ["4-2-3-1", "4-3-3", "4-4-2", "3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "ball-playing-defender",
    name: "Ball-Playing Defender",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Composure", "Vision", "First Touch", "Technique", "Decisions"],
    description: "A center-back who builds play from the back with accurate passing and composure under pressure.",
    bestFormations: ["4-2-3-1", "4-3-3", "3-5-2"],
  },
  {
    id: "central-defender",
    name: "Central Defender",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Tackling", "Marking", "Heading", "Positioning", "Strength", "Jumping Reach"],
    description: "The traditional no-nonsense defender. Wins aerial duels and makes crucial tackles.",
    bestFormations: ["4-4-2", "5-3-2"],
  },
  {
    id: "full-back",
    name: "Full-Back",
    category: "defender",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Tackling", "Stamina", "Acceleration", "Crossing", "Work Rate", "Positioning"],
    description: "Balanced wide defender who supports both attack and defense from the flanks.",
    bestFormations: ["4-2-3-1", "4-3-3", "4-4-2"],
  },
  {
    id: "wing-back",
    name: "Wing-Back",
    category: "defender",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Stamina", "Crossing", "Dribbling", "Acceleration", "Work Rate", "Off the Ball"],
    description: "An attacking-minded wide player who provides the main source of width in formations without wingers.",
    bestFormations: ["3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "deep-lying-playmaker",
    name: "Deep-Lying Playmaker",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Vision", "Technique", "Decisions", "Composure", "First Touch"],
    description: "A midfield orchestrator who dictates tempo from deep positions with incisive passing range.",
    bestFormations: ["4-2-3-1", "4-3-3", "3-5-2"],
  },
  {
    id: "box-to-box-midfielder",
    name: "Box-to-Box Midfielder",
    category: "midfielder",
    availableDuties: ["support"],
    keyAttributes: ["Stamina", "Work Rate", "Passing", "Tackling", "Long Shots", "Off the Ball"],
    description: "An energetic midfielder who contributes at both ends of the pitch with relentless running.",
    bestFormations: ["4-3-3", "4-4-2", "3-5-2"],
  },
  {
    id: "advanced-playmaker",
    name: "Advanced Playmaker",
    category: "midfielder",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Vision", "Passing", "Technique", "Decisions", "Flair", "First Touch"],
    description: "The creative hub operating between the lines, threading through balls and unlocking defenses.",
    bestFormations: ["4-2-3-1", "4-3-3"],
  },
  {
    id: "inside-forward",
    name: "Inside Forward",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Dribbling", "Finishing", "Acceleration", "Off the Ball", "Composure", "Technique"],
    description: "Cuts inside from wide positions to score goals, acting more like a striker than a traditional winger.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "advanced-forward",
    name: "Advanced Forward",
    category: "forward",
    availableDuties: ["attack"],
    keyAttributes: ["Finishing", "Acceleration", "Off the Ball", "Composure", "Anticipation", "Dribbling"],
    description: "The primary goal-scoring outlet who plays on the shoulder of the last defender.",
    bestFormations: ["4-2-3-1", "4-3-3", "4-4-2"],
  },
  {
    id: "pressing-forward",
    name: "Pressing Forward",
    category: "forward",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Work Rate", "Aggression", "Stamina", "Bravery", "Tackling", "Acceleration"],
    description: "A defensive forward who harasses opposition defenders and forces mistakes high up the pitch.",
    bestFormations: ["4-2-3-1", "4-4-2"],
  },
  {
    id: "target-forward",
    name: "Target Forward",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Strength", "Heading", "Jumping Reach", "First Touch", "Bravery", "Balance"],
    description: "A physical presence who holds up the ball and brings teammates into play with knock-downs and layoffs.",
    bestFormations: ["4-4-2", "3-5-2"],
  },
];

export const styleLabels: Record<string, string> = {
  "gegenpress": "Gegenpress",
  "tiki-taka": "Tiki-Taka",
  "counter-attack": "Counter Attack",
  "wing-play": "Wing Play",
  "route-one": "Route One",
  "fluid": "Fluid Attack",
  "fluid-counter-attack": "Fluid Counter",
  "park-the-bus": "Park the Bus",
  "control-possession": "Control Possession",
};

export const styleColors: Record<string, string> = {
  "gegenpress": "bg-red-500/20 text-red-400 border-red-500/30",
  "tiki-taka": "bg-blue-500/20 text-blue-400 border-blue-500/30",
  "counter-attack": "bg-amber-500/20 text-amber-400 border-amber-500/30",
  "wing-play": "bg-purple-500/20 text-purple-400 border-purple-500/30",
  "route-one": "bg-orange-500/20 text-orange-400 border-orange-500/30",
  "fluid": "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
  "fluid-counter-attack": "bg-teal-500/20 text-teal-400 border-teal-500/30",
  "park-the-bus": "bg-slate-500/20 text-slate-400 border-slate-500/30",
  "control-possession": "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
};

export const mentalityDescriptions: Record<string, string> = {
  "very-defensive": "Extreme caution. Players stay behind the ball and rarely commit forward.",
  "defensive": "Prioritizes defensive solidity with selective counter-attacking.",
  "cautious": "Keeps possession and waits for openings without taking unnecessary risks.",
  "balanced": "A measured approach that adapts to game situations.",
  "positive": "Looks to control the game with attacking intent while maintaining defensive structure.",
  "attacking": "High-tempo attacking football focused on creating chances.",
  "very-attacking": "All-out attack. Players flood forward and take constant risks.",
};
