import type {
  FormationType,
  PlayerRoleData,
  FormationPreset,
  PlayerDuty,
} from "@/types/tactic";

export const formationPresets: FormationPreset[] = [
  {
    formation: "4-2-3-1",
    label: "4-2-3-1",
    description: "The modern classic. Two holding midfielders support a creative attacking midfielder with wingers providing width.",
    // Order: GK | LB CB CB RB | DM DM | AML AMC AMR | ST
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 35, y: 52 }, { x: 65, y: 52 },
      { x: 15, y: 34 }, { x: 50, y: 34 }, { x: 85, y: 34 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "4-3-3",
    label: "4-3-3",
    description: "Wide forwards stretch the opposition. Three midfielders offer balance between defense and attack.",
    // Order: GK | LB CB CB RB | CM DM CM | LW ST RW
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 35, y: 44 }, { x: 50, y: 56 }, { x: 65, y: 44 },
      { x: 20, y: 18 }, { x: 50, y: 10 }, { x: 80, y: 18 },
    ],
  },
  {
    formation: "4-4-2",
    label: "4-4-2",
    description: "The traditional English setup. Two banks of four with a classic strike partnership.",
    positions: [
      { x: 50, y: 88 }, { x: 10, y: 55 }, { x: 25, y: 72 }, { x: 75, y: 72 },
      { x: 90, y: 55 }, { x: 10, y: 40 }, { x: 35, y: 42 },
      { x: 65, y: 42 }, { x: 90, y: 40 }, { x: 35, y: 18 },
      { x: 65, y: 18 },
    ],
  },
  {
    formation: "3-5-2",
    label: "3-5-2",
    description: "Wing-backs provide width as three center-backs form a solid defensive base with two strikers.",
    positions: [
      { x: 50, y: 88 }, { x: 32, y: 72 }, { x: 50, y: 74 },
      { x: 68, y: 72 }, { x: 20, y: 46 }, { x: 40, y: 52 },
      { x: 50, y: 44 }, { x: 60, y: 52 }, { x: 80, y: 46 },
      { x: 35, y: 18 }, { x: 65, y: 18 },
    ],
  },
  {
    formation: "5-3-2",
    label: "5-3-2",
    description: "Ultra-defensive shape with wing-backs. Counter-attack specialist formation.",
    positions: [
      { x: 50, y: 88 }, { x: 20, y: 74 }, { x: 50, y: 78 },
      { x: 80, y: 74 }, { x: 10, y: 48 }, { x: 90, y: 48 },
      { x: 35, y: 52 }, { x: 50, y: 42 }, { x: 65, y: 52 },
      { x: 35, y: 18 }, { x: 65, y: 18 },
    ],
  },
  {
    formation: "3-4-3",
    label: "3-4-3",
    description: "Attacking formation with wing-backs pushing high. Three forwards apply constant pressure on opposing defenders.",
    positions: [
      { x: 50, y: 88 }, { x: 32, y: 72 }, { x: 50, y: 74 },
      { x: 68, y: 72 }, { x: 20, y: 46 }, { x: 40, y: 48 },
      { x: 60, y: 48 }, { x: 80, y: 46 }, { x: 25, y: 16 },
      { x: 50, y: 10 }, { x: 75, y: 16 },
    ],
  },
  {
    formation: "4-2-2-2",
    label: "4-2-2-2",
    description: "Brazilian Box. Two DMs and two AMs create a compact midfield box, with two strikers leading the line.",
    // Order: GK | LB CB CB RB | DM DM | AM AM | ST ST
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 35, y: 52 }, { x: 65, y: 52 },
      { x: 35, y: 34 }, { x: 65, y: 34 },
      { x: 35, y: 16 }, { x: 65, y: 16 },
    ],
  },
  {
    formation: "4-1-4-1",
    label: "4-1-4-1",
    description: "A solid DM shields the back four. Four midfielders offer width and numbers in the middle third.",
    // Order: GK | LB CB CB RB | DM | LM CM CM RM | ST
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 50, y: 58 },
      { x: 15, y: 42 }, { x: 38, y: 46 }, { x: 62, y: 46 }, { x: 85, y: 42 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "4-4-1-1",
    label: "4-4-1-1",
    description: "The Mourinho special. A second striker or #10 operates between the lines behind a lone target man.",
    // Order: GK | LB CB CB RB | LM CM CM RM | SS | ST
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 12, y: 46 }, { x: 38, y: 48 }, { x: 62, y: 48 }, { x: 88, y: 46 },
      { x: 50, y: 28 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "5-2-3",
    label: "5-2-3",
    description: "Three center-backs with attacking wing-backs. Wide forwards stretch play and create overloads in the final third.",
    positions: [
      { x: 50, y: 88 }, { x: 25, y: 74 }, { x: 50, y: 78 },
      { x: 75, y: 74 }, { x: 10, y: 48 }, { x: 90, y: 48 },
      { x: 35, y: 50 }, { x: 65, y: 50 },
      { x: 25, y: 16 }, { x: 50, y: 10 }, { x: 75, y: 16 },
    ],
  },
  {
    formation: "4-2-4",
    label: "4-2-4",
    description: "Ultra-attacking shape with four forwards. Risky but devastating — the FM26 community's top-scoring formation in tests.",
    // Order: GK | LB CB CB RB | DM DM (half-spaces) | LW ST ST RW (flat front four)
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 30, y: 50 }, { x: 70, y: 50 },
      { x: 15, y: 18 }, { x: 40, y: 14 }, { x: 60, y: 14 }, { x: 85, y: 18 },
    ],
  },
  {
    formation: "3-4-2-1",
    label: "3-4-2-1",
    description: "Conte's trademark. Two #10s behind a lone striker with wing-backs providing width. Extremely solid through the middle.",
    positions: [
      { x: 50, y: 88 }, { x: 32, y: 72 }, { x: 50, y: 74 },
      { x: 68, y: 72 }, { x: 15, y: 46 }, { x: 85, y: 46 },
      { x: 35, y: 52 }, { x: 65, y: 52 },
      { x: 35, y: 30 }, { x: 65, y: 30 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "4-3-2-1",
    label: "4-3-2-1",
    description: "Christmas Tree. Narrow and compact. Two advanced playmakers operate behind a solo striker, overwhelming the opponent's midfield.",
    // Order: GK | LB CB CB RB | CM CM CM | AM AM | ST (Christmas Tree)
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 30, y: 52 }, { x: 50, y: 48 }, { x: 70, y: 52 },
      { x: 35, y: 30 }, { x: 65, y: 30 },
      { x: 50, y: 12 },
    ],
  },
  {
    formation: "4-1-2-1-2",
    label: "4-1-2-1-2",
    description: "Diamond midfield. A DM anchors, two CMs shuttle, and a #10 creates. Two strikers give you vertical threat against any back line.",
    // Order: GK | LB CB CB RB | DM | CM CM | AM | ST ST (Diamond)
    positions: [
      { x: 50, y: 88 },
      { x: 10, y: 68 }, { x: 35, y: 74 }, { x: 65, y: 74 }, { x: 90, y: 68 },
      { x: 50, y: 58 },
      { x: 30, y: 44 }, { x: 70, y: 44 },
      { x: 50, y: 30 },
      { x: 35, y: 14 }, { x: 65, y: 14 },
    ],
  },
];

export const playerRoles: PlayerRoleData[] = [
  {
    id: "sweeper-keeper",
    name: "Sweeper Keeper",
    abbr: "SK",
    category: "goalkeeper",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Rushing Out", "First Touch", "Passing", "Composure", "Acceleration", "Decisions"],
    description: "A goalkeeper who sweeps up balls behind the defensive line and initiates counter-attacks with long distribution.",
    bestFormations: ["4-2-3-1", "4-3-3", "5-3-2"],
  },
  {
    id: "goalkeeper",
    name: "Goalkeeper",
    abbr: "GK",
    category: "goalkeeper",
    availableDuties: ["defend"],
    keyAttributes: ["Aerial Reach", "Command of Area", "Handling", "Reflexes", "Positioning", "Decisions"],
    description: "The standard goalkeeper role. Stays between the sticks, organizes the defense, and makes saves.",
    bestFormations: ["4-2-3-1", "4-3-3", "4-4-2", "3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "ball-playing-defender",
    name: "Ball-Playing Defender",
    abbr: "BPD",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Composure", "Vision", "First Touch", "Technique", "Decisions"],
    description: "A center-back who builds play from the back with accurate passing and composure under pressure.",
    bestFormations: ["4-2-3-1", "4-3-3", "3-5-2"],
  },
  {
    id: "central-defender",
    name: "Central Defender",
    abbr: "CD",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Tackling", "Marking", "Heading", "Positioning", "Strength", "Jumping Reach"],
    description: "The traditional no-nonsense defender. Wins aerial duels and makes crucial tackles.",
    bestFormations: ["4-4-2", "5-3-2"],
  },
  {
    id: "full-back",
    name: "Full-Back",
    abbr: "FB",
    category: "defender",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Tackling", "Stamina", "Acceleration", "Crossing", "Work Rate", "Positioning"],
    description: "Balanced wide defender who supports both attack and defense from the flanks.",
    bestFormations: ["4-2-3-1", "4-3-3", "4-4-2"],
  },
  {
    id: "wing-back",
    name: "Wing-Back",
    abbr: "WB",
    category: "defender",
    availableDuties: ["defend", "support", "attack"],
    keyAttributes: ["Stamina", "Crossing", "Dribbling", "Acceleration", "Work Rate", "Off the Ball"],
    description: "An attacking-minded wide player who provides the main source of width in formations without wingers.",
    bestFormations: ["3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "deep-lying-playmaker",
    name: "Deep-Lying Playmaker",
    abbr: "DLP",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Vision", "Technique", "Decisions", "Composure", "First Touch"],
    description: "A midfield orchestrator who dictates tempo from deep positions with incisive passing range.",
    bestFormations: ["4-2-3-1", "4-3-3", "3-5-2"],
  },
  {
    id: "box-to-box-midfielder",
    name: "Box-to-Box Midfielder",
    abbr: "BBM",
    category: "midfielder",
    availableDuties: ["support"],
    keyAttributes: ["Stamina", "Work Rate", "Passing", "Tackling", "Long Shots", "Off the Ball"],
    description: "An energetic midfielder who contributes at both ends of the pitch with relentless running.",
    bestFormations: ["4-3-3", "4-4-2", "3-5-2"],
  },
  {
    id: "advanced-playmaker",
    name: "Advanced Playmaker",
    abbr: "AP",
    category: "midfielder",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Vision", "Passing", "Technique", "Decisions", "Flair", "First Touch"],
    description: "The creative hub operating between the lines, threading through balls and unlocking defenses.",
    bestFormations: ["4-2-3-1", "4-3-3"],
  },
  {
    id: "inside-forward",
    name: "Inside Forward",
    abbr: "IF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Dribbling", "Finishing", "Acceleration", "Off the Ball", "Composure", "Technique"],
    description: "Cuts inside from wide positions to score goals, acting more like a striker than a traditional winger.",
    bestFormations: ["4-3-3", "4-2-3-1"],
  },
  {
    id: "target-forward",
    name: "Target Forward",
    abbr: "TF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Strength", "Heading", "Jumping Reach", "First Touch", "Bravery", "Balance"],
    description: "A physical presence who holds up the ball and brings teammates into play with knock-downs and layoffs.",
    bestFormations: ["4-4-2", "3-5-2"],
  },
  // === FM26 NEW ROLES ===
  {
    id: "line-holding-keeper",
    name: "Line-Holding Keeper",
    abbr: "LHK",
    category: "goalkeeper",
    availableDuties: ["defend"],
    keyAttributes: ["Aerial Reach", "Reflexes", "Handling", "Positioning", "Command of Area", "Decisions"],
    description: "A traditional goalkeeper introduced in FM26 who holds his line and stays deep — ideal for defences that sit back and protect the box.",
    bestFormations: ["4-4-2", "5-3-2", "4-2-3-1"],
  },
  {
    id: "overlapping-centre-back",
    name: "Overlapping Centre-Back",
    abbr: "OCB",
    category: "defender",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Pace", "Off the Ball", "Passing", "Work Rate", "Acceleration", "Positioning"],
    description: "A FM26 centre-back role for three-at-the-back systems who steps out and overlaps on the flank, adding an extra body in the final third.",
    bestFormations: ["3-5-2", "5-3-2", "3-4-3"],
  },
  {
    id: "playmaking-wing-back",
    name: "Playmaking Wing-Back",
    abbr: "PWB",
    category: "defender",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Passing", "Crossing", "Vision", "Dribbling", "Work Rate", "Stamina"],
    description: "The advanced FM26 wing-back role that drifts inside to dictate play, creating overloads while the wide forward stretches the pitch.",
    bestFormations: ["3-5-2", "3-4-3", "5-2-3"],
  },
  {
    id: "channel-midfielder",
    name: "Channel Midfielder",
    abbr: "CHM",
    category: "midfielder",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Off the Ball", "Acceleration", "Passing", "First Touch", "Decisions", "Teamwork"],
    description: "A new FM26 midfielder who attacks the half-spaces between the lines, arriving late in the box and combining between midfield and attack.",
    bestFormations: ["4-3-3", "4-2-3-1", "3-4-3"],
  },
  // === FM26 STANDARD ROLES (real in-game names) ===
  {
    id: "central-midfielder",
    name: "Central Midfielder",
    abbr: "CM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Passing", "Tackling", "Stamina", "Positioning", "Teamwork", "Decisions"],
    description: "The all-round central midfielder who keeps the team's shape, recycling possession and plugging gaps on both sides of the ball.",
    bestFormations: ["4-4-2", "4-3-3"],
  },
  {
    id: "winger",
    name: "Winger",
    abbr: "W",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Crossing", "Dribbling", "Pace", "Acceleration", "Technique", "Agility"],
    description: "The traditional wide attacker who hugs the touchline, beats his man and delivers crosses from the byline.",
    bestFormations: ["4-3-3", "4-2-3-1", "4-4-2", "4-2-4"],
  },
  {
    id: "tracking-winger",
    name: "Tracking Winger",
    abbr: "TW",
    category: "forward",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Stamina", "Pace", "Tackling", "Marking", "Teamwork"],
    description: "An FM26 out-of-possession wide role that tracks opposition full-backs up and down the flank before attacking on the turn.",
    bestFormations: ["3-4-3", "4-4-2"],
  },
  {
    id: "pressing-central-midfielder",
    name: "Pressing Central Midfielder",
    abbr: "PCM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Tackling", "Aggression", "Work Rate", "Stamina", "Anticipation", "Positioning"],
    description: "FM26's ball-winning engine — hunts possession relentlessly in midfield and feeds teammates with simple, secure passes.",
    bestFormations: ["4-4-2", "4-2-3-1", "3-5-2"],
  },
  {
    id: "defensive-midfielder",
    name: "Defensive Midfielder",
    abbr: "DM",
    category: "midfielder",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Tackling", "Positioning", "Marking", "Strength", "Anticipation", "Concentration"],
    description: "The anchor of the midfield who sits in front of the back line, screening passes into central areas.",
    bestFormations: ["4-2-3-1", "4-1-2-1-2", "4-4-2"],
  },
  {
    id: "attacking-midfielder",
    name: "Attacking Midfielder",
    abbr: "AM",
    category: "midfielder",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Vision", "Passing", "Technique", "Off the Ball", "Flair", "Long Shots"],
    description: "A central creator in the hole between the opposition midfield and defence, linking play and arriving late in the box.",
    bestFormations: ["4-2-3-1", "4-1-2-1-2"],
  },
  {
    id: "wide-covering-central-midfielder",
    name: "Wide Covering Central Midfielder",
    abbr: "WCC",
    category: "midfielder",
    availableDuties: ["support"],
    keyAttributes: ["Stamina", "Work Rate", "Positioning", "Teamwork", "Tackling", "Pace"],
    description: "FM26's renamed Carrilero — shuttles laterally to cover the half-space and flank left by attacking full-backs and wing-backs.",
    bestFormations: ["4-1-2-1-2", "3-5-2"],
  },
  {
    id: "centre-forward",
    name: "Centre Forward",
    abbr: "CF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["Finishing", "First Touch", "Off the Ball", "Composure", "Strength", "Heading"],
    description: "FM26's complete striker — leads the line, links play and finishes inside the box, the spiritual successor to the Complete Forward.",
    bestFormations: ["4-3-3", "4-2-3-1", "3-4-3"],
  },
  {
    id: "deep-lying-forward",
    name: "Deep-Lying Forward",
    abbr: "DLF",
    category: "forward",
    availableDuties: ["support", "attack"],
    keyAttributes: ["First Touch", "Passing", "Vision", "Composure", "Off the Ball", "Technique"],
    description: "Drops off the defensive line to link midfield and attack, creating space for runners from deep.",
    bestFormations: ["4-1-2-1-2", "4-2-3-1", "4-4-2"],
  },
  {
    id: "free-role",
    name: "Free Role",
    abbr: "FR",
    category: "midfielder",
    availableDuties: ["attack"],
    keyAttributes: ["Flair", "Vision", "First Touch", "Technique", "Off the Ball", "Composure"],
    description: "FM26's successor to the Trequartista — roams the final third with a free licence to create, unbound by tactical shape.",
    bestFormations: ["4-2-3-1", "4-4-1-1"],
  },
  {
    id: "tracking-centre-forward",
    name: "Tracking Centre Forward",
    abbr: "TCF",
    category: "forward",
    availableDuties: ["defend", "support"],
    keyAttributes: ["Work Rate", "Stamina", "Aggression", "Tackling", "Teamwork", "Acceleration"],
    description: "A new FM26 striker who leads the press from the front and drops back to bolster midfield when defending.",
    bestFormations: ["4-2-3-1", "4-3-3"],
  },
];

export const styleLabels: Record<string, string> = {
  "gegenpress": "Gegenpress",
  "tiki-taka": "Tiki-Taka",
  "counter-attack": "Counter Attack",
  "wing-play": "Wing Play",
  "route-one": "Route One",
  "fluid": "Fluid Attack",
  "fluid-counter-attack": "Fluid Counter",
  "park-the-bus": "Park the Bus",
  "control-possession": "Control Possession",
};

export const styleColors: Record<string, string> = {
  "gegenpress": "bg-red-500/20 text-red-400 border-red-500/30",
  "tiki-taka": "bg-blue-500/20 text-blue-400 border-blue-500/30",
  "counter-attack": "bg-amber-500/20 text-amber-400 border-amber-500/30",
  "wing-play": "bg-purple-500/20 text-purple-400 border-purple-500/30",
  "route-one": "bg-orange-500/20 text-orange-400 border-orange-500/30",
  "fluid": "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
  "fluid-counter-attack": "bg-teal-500/20 text-teal-400 border-teal-500/30",
  "park-the-bus": "bg-slate-500/20 text-slate-400 border-slate-500/30",
  "control-possession": "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
};

export const mentalityDescriptions: Record<string, string> = {
  "very-defensive": "Extreme caution. Players stay behind the ball and rarely commit forward.",
  "defensive": "Prioritizes defensive solidity with selective counter-attacking.",
  "cautious": "Keeps possession and waits for openings without taking unnecessary risks.",
  "balanced": "A measured approach that adapts to game situations.",
  "positive": "Looks to control the game with attacking intent while maintaining defensive structure.",
  "attacking": "High-tempo attacking football focused on creating chances.",
  "very-attacking": "All-out attack. Players flood forward and take constant risks.",
};
