"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import { trackEvent } from "@/lib/analytics";
import { formationPresets, playerRoles } from "@/lib/tactics-data";
import type { TacticTemplate } from "@/lib/tactic-templates";
import type {
  FormationPreset,
  FormationType,
  PlayerNode,
  TeamInstruction,
  TacticBoardState,
  TacticPhases,
  PhaseType,
  PlayerMovement,
  Mentality,
  PlayerDuty,
} from "@/types/tactic";

const STORAGE_KEY = "fm26tactics_builder_draft_v1";
const SAVE_DELAY_MS = 400;

export const PHASE_VALUES: PhaseType[] = ["in-possession", "out-of-possession"];

function isValidPhaseMap(map: unknown, players: PlayerNode[]): boolean {
  if (!map || typeof map !== "object") return false;
  // Every current player must have a valid phase entry (drafts saved across a
  // formation change can drift — those get regenerated by ensurePhases).
  return players.every((p) => {
    const entry = (map as Record<string, unknown>)[p.id];
    return (
      entry &&
      typeof entry === "object" &&
      typeof (entry as { x?: unknown }).x === "number" &&
      typeof (entry as { y?: unknown }).y === "number"
    );
  });
}

/**
 * Migrate legacy tactic data (no phases) by duplicating the base positions
 * into both phases — roles, duties and team instructions stay untouched.
 */
/** Always rebuild both phase maps from the given players, discarding phase edits. */
function freshPhases(players: PlayerNode[]): TacticPhases {
  return {
    "in-possession": Object.fromEntries(
      players.map((p) => [p.id, { x: p.x, y: p.y }])
    ),
    "out-of-possession": Object.fromEntries(
      players.map((p) => [p.id, { x: p.x, y: p.y }])
    ),
  };
}

export function ensurePhases(state: TacticBoardState): TacticBoardState {
  if (
    state.phases &&
    isValidPhaseMap(state.phases["in-possession"], state.players) &&
    isValidPhaseMap(state.phases["out-of-possession"], state.players)
  ) {
    return state;
  }
  return {
    ...state,
    phases: freshPhases(state.players),
  };
}

/** Players as displayed in a phase: base identities, phase coordinates. */
export function resolvePhasePlayers(
  state: TacticBoardState,
  phase: PhaseType
): PlayerNode[] {
  const map = state.phases?.[phase];
  if (!map) return state.players;
  return state.players.map((p) => {
    const entry = map[p.id];
    return entry ? { ...p, x: entry.x, y: entry.y } : p;
  });
}

function isValidTacticState(value: unknown): value is TacticBoardState {
  if (!value || typeof value !== "object") return false;
  const v = value as Partial<TacticBoardState>;
  if (typeof v.formation !== "string") return false;
  // Football is 11-a-side; reject legacy drafts/links/imports with wrong counts
  if (!Array.isArray(v.players) || v.players.length !== 11) return false;
  const playersOk = v.players.every(
    (p) =>
      p &&
      typeof p.id === "string" &&
      typeof p.x === "number" &&
      typeof p.y === "number" &&
      typeof p.roleId === "string" &&
      (p.duty === "defend" || p.duty === "support" || p.duty === "attack")
  );
  if (!playersOk) return false;
  const ti = v.teamInstructions as Partial<TeamInstruction> | undefined;
  if (!ti || typeof ti !== "object") return false;
  return (
    typeof ti.mentality === "string" &&
    Array.isArray(ti.inPossession) &&
    Array.isArray(ti.inTransition) &&
    Array.isArray(ti.outOfPossession)
  );
}

/** Encode a tactic state into a compact URL-safe string. */
export function encodeTacticState(state: TacticBoardState): string {
  return btoa(unescape(encodeURIComponent(JSON.stringify(state))));
}

/** Decode a URL-encoded tactic state, or null if invalid. Legacy payloads without phases are migrated on decode. */
export function decodeTacticState(encoded: string): TacticBoardState | null {
  try {
    const json = decodeURIComponent(escape(atob(encoded)));
    const parsed = JSON.parse(json);
    return isValidTacticState(parsed) ? ensurePhases(parsed) : null;
  } catch {
    return null;
  }
}

/**
 * Build a URL-ready `tactic` param from a content tactic's frontmatter setup,
 * so "Try in Builder" loads the exact 11 roles/duties/positions shown on the
 * tactic page instead of the formation's default preset.
 * Returns the encodeURIComponent'd payload, or null when the setup can't form
 * a valid 11-a-side board (caller should fall back to `?formation=`).
 */
export function encodeTacticSetupParam(
  formation: string,
  setup: ReadonlyArray<{ roleId: string; duty: string; x: number; y: number }> | undefined
): string | null {
  if (!setup || setup.length !== 11) return null;
  const preset = formationPresets.find((f) => f.formation === formation);
  if (!preset) return null;
  const players: PlayerNode[] = [];
  for (let i = 0; i < setup.length; i++) {
    const s = setup[i];
    const role = playerRoles.find((r) => r.id === s.roleId);
    if (!role || typeof s.x !== "number" || typeof s.y !== "number") return null;
    const duty = (role.availableDuties as readonly string[]).includes(s.duty)
      ? (s.duty as PlayerDuty)
      : role.availableDuties[0] || "support";
    players.push({
      id: `player-${i}`,
      x: s.x,
      y: s.y,
      roleId: s.roleId,
      duty,
      individualInstructions: [],
    });
  }
  const state: TacticBoardState = {
    formation: preset.formation,
    players,
    teamInstructions: {
      mentality: "balanced",
      inPossession: [],
      inTransition: [],
      outOfPossession: [],
    },
  };
  return encodeURIComponent(encodeTacticState(ensurePhases(state)));
}

function createDefaultState(): TacticBoardState {
  return createDefaultStateForFormation(formationPresets[0].formation as FormationType);
}

/**
 * Build the 11 starting players for a formation preset. Roles/duties come from
 * `preset.defaultRoles` — transcribed from the formation's deep-dive tactic
 * article (content/tactics/*.mdx `setup`) — with validated duty fallbacks.
 * Existing player ids are reused when provided so draft/phase data stays keyed.
 */
function buildPresetPlayers(preset: FormationPreset, prevPlayers?: PlayerNode[]): PlayerNode[] {
  const fallbackPool = playerRoles.filter((r) => r.category !== "goalkeeper");
  return preset.positions.map((pos, i) => {
    const fallbackRole =
      i === 0
        ? playerRoles.find((r) => r.id === "sweeper-keeper") || playerRoles[0]
        : fallbackPool[i % fallbackPool.length] || fallbackPool[0];
    const assignment = preset.defaultRoles?.[i];
    const role = assignment
      ? playerRoles.find((r) => r.id === assignment.roleId)
      : undefined;
    const resolved = role ?? fallbackRole;
    const duty =
      assignment && resolved.availableDuties.includes(assignment.duty)
        ? assignment.duty
        : resolved.availableDuties[0] || "support";
    return {
      id: prevPlayers?.[i]?.id ?? `player-${i}`,
      x: pos.x,
      y: pos.y,
      roleId: resolved.id,
      duty,
      individualInstructions: [],
    };
  });
}

function createDefaultStateForFormation(formation: FormationType): TacticBoardState {
  const preset = formationPresets.find((f) => f.formation === formation);
  if (!preset) return createDefaultStateForFormation(formationPresets[0].formation as FormationType);
  const base: TacticBoardState = {
    formation: preset.formation,
    players: buildPresetPlayers(preset),
    teamInstructions: {
      mentality: "balanced",
      inPossession: [],
      inTransition: [],
      outOfPossession: [],
    },
  };
  return ensurePhases(base);
}

function loadInitialState(): TacticBoardState {
  if (typeof window !== "undefined") {
    // 1. Shared tactic via URL (?tactic=...) takes priority
    const encoded = new URLSearchParams(window.location.search).get("tactic");
    if (encoded) {
      const decoded = decodeTacticState(encoded);
      if (decoded) return decoded;
    }
    // 2. Formation preset via URL (?formation=4-2-3-1)
    const formationParam = new URLSearchParams(window.location.search).get("formation");
    if (formationParam) {
      const preset = formationPresets.find((f) => f.formation === formationParam);
      if (preset) {
        return createDefaultStateForFormation(preset.formation as FormationType);
      }
    }
    // 3. Last saved draft
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (isValidTacticState(parsed)) return ensurePhases(parsed);
      }
    } catch {
      // ignore corrupted storage
    }
  }
  return createDefaultState();
}

function loadInitialPhase(): PhaseType {
  if (typeof window !== "undefined") {
    const param = new URLSearchParams(window.location.search).get("phase");
    if (param === "out-of-possession") return "out-of-possession";
  }
  return "in-possession";
}

export function useTacticBuilder() {
  const [state, setState] = useState<TacticBoardState>(loadInitialState);
  const [activePhase, setActivePhaseState] = useState<PhaseType>(loadInitialPhase);
  const [sharedLoadMsg, setSharedLoadMsg] = useState<"ok" | "fail" | null>(null);
  const sharedTrackedRef = useRef(false);
  const formationAppliedRef = useRef(false);

  /** Switch the phase view and mirror it into the ?phase= URL param. */
  const setActivePhase = useCallback((phase: PhaseType) => {
    setActivePhaseState(phase);
    if (typeof window !== "undefined") {
      const url = new URL(window.location.href);
      url.searchParams.set("phase", phase);
      window.history.replaceState(null, "", url);
    }
    trackEvent("builder_phase_switch", { label: phase });
  }, []);

  // Apply ?formation= URL param on client mount (useState initializer
  // runs during SSR where window is unavailable, so we need this effect)
  useEffect(() => {
    if (formationAppliedRef.current) return;
    if (typeof window === "undefined") return;
    const formationParam = new URLSearchParams(window.location.search).get("formation");
    if (!formationParam) return;
    const preset = formationPresets.find((f) => f.formation === formationParam);
    if (!preset) return;
    formationAppliedRef.current = true;
    setState(createDefaultStateForFormation(preset.formation as FormationType));
    trackEvent("builder_formation_url_load", { label: preset.formation });
  }, []);

  // Apply ?tactic= URL param on client mount and fire shared-link tracking.
  // The useState initializer runs during SSR where window is unavailable,
  // so — like the ?formation= effect above — we must re-read the param here
  // and call setState to ensure the shared tactic actually loads.
  // The ref guards against StrictMode's double effect run in dev.
  useEffect(() => {
    if (sharedTrackedRef.current) return;
    const encoded =
      typeof window !== "undefined"
        ? new URLSearchParams(window.location.search).get("tactic")
        : null;
    if (!encoded) return;
    sharedTrackedRef.current = true;
    const decoded = decodeTacticState(encoded);
    trackEvent("builder_shared_load", { label: decoded ? "ok" : "fail" });
    if (decoded) {
      setState(decoded);
      setSharedLoadMsg("ok");
      setTimeout(() => setSharedLoadMsg(null), 5000);
    }
  }, []);

  // Auto-save draft to localStorage (debounced)
  useEffect(() => {
    const timer = setTimeout(() => {
      try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
      } catch {
        // storage unavailable — ignore
      }
    }, SAVE_DELAY_MS);
    return () => clearTimeout(timer);
  }, [state]);

  const setFormation = useCallback((formation: FormationType) => {
    const preset = formationPresets.find((f) => f.formation === formation);
    if (!preset) return;

    setState((prev) => {
      // Roles/duties reset to the formation's default XI (from its deep-dive
      // tactic article) — each formation ships its own curated role set.
      const players = buildPresetPlayers(preset, prev.players);
      // New formation → force-regenerate both phases from the fresh preset
      // positions. ensurePhases alone would keep the old (still-valid)
      // coordinates because player ids are stable across formations.
      return { ...prev, formation, players, phases: freshPhases(players) };
    });
  }, []);

  const movePlayer = useCallback((playerId: string, x: number, y: number, snap = false) => {
    const clampedX = Math.max(5, Math.min(95, x));
    const clampedY = Math.max(5, Math.min(95, y));
    const finalX = snap ? Math.round(clampedX / 2.5) * 2.5 : clampedX;
    const finalY = snap ? Math.round(clampedY / 2.5) * 2.5 : clampedY;

    setState((prev) => {
      const migrated = ensurePhases(prev);
      if (!migrated.phases) return prev;
      const phaseMap = migrated.phases[activePhase];
      const entry = phaseMap[playerId];
      if (!entry) return prev;
      return {
        ...prev,
        phases: {
          ...migrated.phases,
          [activePhase]: {
            ...phaseMap,
            [playerId]: { ...entry, x: finalX, y: finalY },
          },
        },
      };
    });
  }, [activePhase]);

  /** Set or clear the tactical-intent movement arrow for a player in the active phase. */
  const setPlayerMovement = useCallback((playerId: string, movement: PlayerMovement | null) => {
    setState((prev) => {
      const migrated = ensurePhases(prev);
      if (!migrated.phases) return prev;
      const phaseMap = migrated.phases[activePhase];
      const entry = phaseMap[playerId];
      if (!entry) return prev;
      return {
        ...prev,
        phases: {
          ...migrated.phases,
          [activePhase]: {
            ...phaseMap,
            [playerId]: { ...entry, movement: movement ?? undefined },
          },
        },
      };
    });
  }, [activePhase]);

  /** Reset every player's position in the active phase back to the base formation. */
  const resetPhasePositions = useCallback(() => {
    setState((prev) => {
      const phases = ensurePhases(prev).phases;
      if (!phases) return prev;
      return {
        ...prev,
        phases: {
          ...phases,
          [activePhase]: Object.fromEntries(
            prev.players.map((p) => [p.id, { x: p.x, y: p.y }])
          ),
        },
      };
    });
    trackEvent("builder_phase_reset", { label: activePhase });
  }, [activePhase]);

  const setPlayerRole = useCallback((playerId: string, roleId: string) => {
    const role = playerRoles.find((r) => r.id === roleId);
    if (!role) return;

    setState((prev) => ({
      ...prev,
      players: prev.players.map((p) =>
        p.id === playerId
          ? {
              ...p,
              roleId,
              duty: role.availableDuties[0] || p.duty,
            }
          : p
      ),
    }));
  }, []);

  const setPlayerDuty = useCallback((playerId: string, duty: PlayerDuty) => {
    setState((prev) => ({
      ...prev,
      players: prev.players.map((p) =>
        p.id === playerId ? { ...p, duty } : p
      ),
    }));
  }, []);

  const setTeamMentality = useCallback((mentality: Mentality) => {
    setState((prev) => ({
      ...prev,
      teamInstructions: { ...prev.teamInstructions, mentality },
    }));
  }, []);

  const toggleInstruction = useCallback(
    (category: "inPossession" | "inTransition" | "outOfPossession", instruction: string) => {
      setState((prev) => {
        const current = prev.teamInstructions[category];
        const updated = current.includes(instruction)
          ? current.filter((i) => i !== instruction)
          : [...current, instruction];

        return {
          ...prev,
          teamInstructions: {
            ...prev.teamInstructions,
            [category]: updated,
          },
        };
      });
    },
    []
  );

  /** One-click apply of a curated meta tactic template. */
  const applyTemplate = useCallback((template: TacticTemplate) => {
    const preset = formationPresets.find((f) => f.formation === template.formation);
    if (!preset) return;

    const roles = playerRoles.filter((r) => r.category !== "goalkeeper");
    const players = preset.positions.map((pos, i) => {
      const assignment = template.roleAssignments[i];
      const role = assignment
        ? playerRoles.find((r) => r.id === assignment.roleId)
        : undefined;
      const fallback = i === 0
        ? playerRoles.find((r) => r.id === "sweeper-keeper") || playerRoles[0]
        : roles[i % roles.length] || roles[0];
      const chosen = role || fallback;
      return {
        id: `player-${i}`,
        x: pos.x,
        y: pos.y,
        roleId: chosen.id,
        duty: assignment?.duty || chosen.availableDuties[0] || "support",
        individualInstructions: [],
      };
    });
    // One-click apply → reset phase edits to the template's base positions
    setState({
      formation: template.formation,
      players,
      teamInstructions: {
        mentality: template.mentality,
        inPossession: [...template.inPossession],
        inTransition: [...template.inTransition],
        outOfPossession: [...template.outOfPossession],
      },
      phases: freshPhases(players),
    });
  }, []);

  const resetTactic = useCallback(() => {
    try {
      localStorage.removeItem(STORAGE_KEY);
    } catch {
      // ignore
    }
    setState(createDefaultState());
  }, []);

  /** Load a tactic from an external source (e.g. imported .json). Returns false if invalid. */
  const loadTactic = useCallback((value: unknown) => {
    if (!isValidTacticState(value)) return false;
    setState(ensurePhases(value));
    return true;
  }, []);

  return {
    state,
    activePhase,
    setActivePhase,
    setFormation,
    movePlayer,
    setPlayerMovement,
    resetPhasePositions,
    setPlayerRole,
    setPlayerDuty,
    setTeamMentality,
    toggleInstruction,
    applyTemplate,
    resetTactic,
    loadTactic,
    sharedLoadMsg,
  };
}

export type { PlayerNode };
